# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/hubertgiza/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Users/hubertgiza/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hubertgiza/CLionProjects/SysOp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hubertgiza/CLionProjects/SysOp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/hubertgiza/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/CLion.app/Contents/bin/cmake/mac/bin/cmake" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/hubertgiza/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/203.7717.62/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hubertgiza/CLionProjects/SysOp/CMakeFiles /Users/hubertgiza/CLionProjects/SysOp/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hubertgiza/CLionProjects/SysOp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named l2_z4

# Build rule for target.
l2_z4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 l2_z4
.PHONY : l2_z4

# fast build rule for target.
l2_z4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z4.dir/build.make CMakeFiles/l2_z4.dir/build
.PHONY : l2_z4/fast

#=============================================================================
# Target rules for targets named l2_z3

# Build rule for target.
l2_z3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 l2_z3
.PHONY : l2_z3

# fast build rule for target.
l2_z3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z3.dir/build.make CMakeFiles/l2_z3.dir/build
.PHONY : l2_z3/fast

#=============================================================================
# Target rules for targets named l2_z2

# Build rule for target.
l2_z2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 l2_z2
.PHONY : l2_z2

# fast build rule for target.
l2_z2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z2.dir/build.make CMakeFiles/l2_z2.dir/build
.PHONY : l2_z2/fast

#=============================================================================
# Target rules for targets named l2_z1

# Build rule for target.
l2_z1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 l2_z1
.PHONY : l2_z1

# fast build rule for target.
l2_z1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z1.dir/build.make CMakeFiles/l2_z1.dir/build
.PHONY : l2_z1/fast

#=============================================================================
# Target rules for targets named library

# Build rule for target.
library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 library
.PHONY : library

# fast build rule for target.
library/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/build
.PHONY : library/fast

#=============================================================================
# Target rules for targets named main_lab1

# Build rule for target.
main_lab1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_lab1
.PHONY : main_lab1

# fast build rule for target.
main_lab1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_lab1.dir/build.make CMakeFiles/main_lab1.dir/build
.PHONY : main_lab1/fast

#=============================================================================
# Target rules for targets named SysOp

# Build rule for target.
SysOp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SysOp
.PHONY : SysOp

# fast build rule for target.
SysOp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysOp.dir/build.make CMakeFiles/SysOp.dir/build
.PHONY : SysOp/fast

Lab_01/zad_1/library.o: Lab_01/zad_1/library.c.o

.PHONY : Lab_01/zad_1/library.o

# target to build an object file
Lab_01/zad_1/library.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/Lab_01/zad_1/library.c.o
.PHONY : Lab_01/zad_1/library.c.o

Lab_01/zad_1/library.i: Lab_01/zad_1/library.c.i

.PHONY : Lab_01/zad_1/library.i

# target to preprocess a source file
Lab_01/zad_1/library.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/Lab_01/zad_1/library.c.i
.PHONY : Lab_01/zad_1/library.c.i

Lab_01/zad_1/library.s: Lab_01/zad_1/library.c.s

.PHONY : Lab_01/zad_1/library.s

# target to generate assembly for a file
Lab_01/zad_1/library.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library.dir/build.make CMakeFiles/library.dir/Lab_01/zad_1/library.c.s
.PHONY : Lab_01/zad_1/library.c.s

Lab_01/zad_1/main.o: Lab_01/zad_1/main.c.o

.PHONY : Lab_01/zad_1/main.o

# target to build an object file
Lab_01/zad_1/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_lab1.dir/build.make CMakeFiles/main_lab1.dir/Lab_01/zad_1/main.c.o
.PHONY : Lab_01/zad_1/main.c.o

Lab_01/zad_1/main.i: Lab_01/zad_1/main.c.i

.PHONY : Lab_01/zad_1/main.i

# target to preprocess a source file
Lab_01/zad_1/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_lab1.dir/build.make CMakeFiles/main_lab1.dir/Lab_01/zad_1/main.c.i
.PHONY : Lab_01/zad_1/main.c.i

Lab_01/zad_1/main.s: Lab_01/zad_1/main.c.s

.PHONY : Lab_01/zad_1/main.s

# target to generate assembly for a file
Lab_01/zad_1/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_lab1.dir/build.make CMakeFiles/main_lab1.dir/Lab_01/zad_1/main.c.s
.PHONY : Lab_01/zad_1/main.c.s

Lab_02/zad_1/zad_1.o: Lab_02/zad_1/zad_1.c.o

.PHONY : Lab_02/zad_1/zad_1.o

# target to build an object file
Lab_02/zad_1/zad_1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z1.dir/build.make CMakeFiles/l2_z1.dir/Lab_02/zad_1/zad_1.c.o
.PHONY : Lab_02/zad_1/zad_1.c.o

Lab_02/zad_1/zad_1.i: Lab_02/zad_1/zad_1.c.i

.PHONY : Lab_02/zad_1/zad_1.i

# target to preprocess a source file
Lab_02/zad_1/zad_1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z1.dir/build.make CMakeFiles/l2_z1.dir/Lab_02/zad_1/zad_1.c.i
.PHONY : Lab_02/zad_1/zad_1.c.i

Lab_02/zad_1/zad_1.s: Lab_02/zad_1/zad_1.c.s

.PHONY : Lab_02/zad_1/zad_1.s

# target to generate assembly for a file
Lab_02/zad_1/zad_1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z1.dir/build.make CMakeFiles/l2_z1.dir/Lab_02/zad_1/zad_1.c.s
.PHONY : Lab_02/zad_1/zad_1.c.s

Lab_02/zad_2/zad_2.o: Lab_02/zad_2/zad_2.c.o

.PHONY : Lab_02/zad_2/zad_2.o

# target to build an object file
Lab_02/zad_2/zad_2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z2.dir/build.make CMakeFiles/l2_z2.dir/Lab_02/zad_2/zad_2.c.o
.PHONY : Lab_02/zad_2/zad_2.c.o

Lab_02/zad_2/zad_2.i: Lab_02/zad_2/zad_2.c.i

.PHONY : Lab_02/zad_2/zad_2.i

# target to preprocess a source file
Lab_02/zad_2/zad_2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z2.dir/build.make CMakeFiles/l2_z2.dir/Lab_02/zad_2/zad_2.c.i
.PHONY : Lab_02/zad_2/zad_2.c.i

Lab_02/zad_2/zad_2.s: Lab_02/zad_2/zad_2.c.s

.PHONY : Lab_02/zad_2/zad_2.s

# target to generate assembly for a file
Lab_02/zad_2/zad_2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z2.dir/build.make CMakeFiles/l2_z2.dir/Lab_02/zad_2/zad_2.c.s
.PHONY : Lab_02/zad_2/zad_2.c.s

Lab_02/zad_3/zad_3.o: Lab_02/zad_3/zad_3.c.o

.PHONY : Lab_02/zad_3/zad_3.o

# target to build an object file
Lab_02/zad_3/zad_3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z3.dir/build.make CMakeFiles/l2_z3.dir/Lab_02/zad_3/zad_3.c.o
.PHONY : Lab_02/zad_3/zad_3.c.o

Lab_02/zad_3/zad_3.i: Lab_02/zad_3/zad_3.c.i

.PHONY : Lab_02/zad_3/zad_3.i

# target to preprocess a source file
Lab_02/zad_3/zad_3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z3.dir/build.make CMakeFiles/l2_z3.dir/Lab_02/zad_3/zad_3.c.i
.PHONY : Lab_02/zad_3/zad_3.c.i

Lab_02/zad_3/zad_3.s: Lab_02/zad_3/zad_3.c.s

.PHONY : Lab_02/zad_3/zad_3.s

# target to generate assembly for a file
Lab_02/zad_3/zad_3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z3.dir/build.make CMakeFiles/l2_z3.dir/Lab_02/zad_3/zad_3.c.s
.PHONY : Lab_02/zad_3/zad_3.c.s

Lab_02/zad_4/zad_4.o: Lab_02/zad_4/zad_4.c.o

.PHONY : Lab_02/zad_4/zad_4.o

# target to build an object file
Lab_02/zad_4/zad_4.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z4.dir/build.make CMakeFiles/l2_z4.dir/Lab_02/zad_4/zad_4.c.o
.PHONY : Lab_02/zad_4/zad_4.c.o

Lab_02/zad_4/zad_4.i: Lab_02/zad_4/zad_4.c.i

.PHONY : Lab_02/zad_4/zad_4.i

# target to preprocess a source file
Lab_02/zad_4/zad_4.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z4.dir/build.make CMakeFiles/l2_z4.dir/Lab_02/zad_4/zad_4.c.i
.PHONY : Lab_02/zad_4/zad_4.c.i

Lab_02/zad_4/zad_4.s: Lab_02/zad_4/zad_4.c.s

.PHONY : Lab_02/zad_4/zad_4.s

# target to generate assembly for a file
Lab_02/zad_4/zad_4.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_z4.dir/build.make CMakeFiles/l2_z4.dir/Lab_02/zad_4/zad_4.c.s
.PHONY : Lab_02/zad_4/zad_4.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysOp.dir/build.make CMakeFiles/SysOp.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysOp.dir/build.make CMakeFiles/SysOp.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SysOp.dir/build.make CMakeFiles/SysOp.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SysOp"
	@echo "... l2_z1"
	@echo "... l2_z2"
	@echo "... l2_z3"
	@echo "... l2_z4"
	@echo "... library"
	@echo "... main_lab1"
	@echo "... Lab_01/zad_1/library.o"
	@echo "... Lab_01/zad_1/library.i"
	@echo "... Lab_01/zad_1/library.s"
	@echo "... Lab_01/zad_1/main.o"
	@echo "... Lab_01/zad_1/main.i"
	@echo "... Lab_01/zad_1/main.s"
	@echo "... Lab_02/zad_1/zad_1.o"
	@echo "... Lab_02/zad_1/zad_1.i"
	@echo "... Lab_02/zad_1/zad_1.s"
	@echo "... Lab_02/zad_2/zad_2.o"
	@echo "... Lab_02/zad_2/zad_2.i"
	@echo "... Lab_02/zad_2/zad_2.s"
	@echo "... Lab_02/zad_3/zad_3.o"
	@echo "... Lab_02/zad_3/zad_3.i"
	@echo "... Lab_02/zad_3/zad_3.s"
	@echo "... Lab_02/zad_4/zad_4.o"
	@echo "... Lab_02/zad_4/zad_4.i"
	@echo "... Lab_02/zad_4/zad_4.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

